project:
  type: website

website:
  title: "Audrey Johnson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
      - text: CV
      - href: contact.qmd
      - text: Contact
      - href: blog.qmd
      - text: Blog
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

